#! /bin/sh

wmname LG3D &
vmware-user-suid-wrapper &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# RESOLUCION ARANDR
xrandr -s 1280x800
#xrandr -s 1280x800 --dpi 90
#xrandr --output Virtual1 -s 1920x1080 --scale 0.8x0.8
#xrandr -s 1920x1080
#xrandr --output Virtual1 --scale 0.8x0.8 --dpi 130
#xrandr --output Virtual1 --fb 1920x1080 --panning 1920x1080 

# WALLPAPER
feh --bg-scale ~/Wallpaper/rosario_vampire.png

# POLYBAR
#~/.config/polybar/launch.sh
$HOME/polybar-collection/launch.sh

# CUSTOM
bspc config focus_follows_pointer true

# PICOM
#picom &
#bspc config border_width 0
picom --experimental-backends &
bspc config border_width 0

xsetroot -cursor_name left_ptr &
